import { GeistSans } from "geist/font/sans";

import "./globals.css";
// import { cookieToInitialState } from "@alchemy/aa-alchemy/config";
import { Providers } from "./provider";
import { headers } from "next/headers";
import { config } from "./config";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
